### ISSUE TITLE
stayinsert error

### ISSUE THREAD

**Issue by bob-moore** [RCS337/HollyHotel#3]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax;

Happens regardless of what data I pass it, all data or just the reservationID, roomID, and Billing ID with the rest null.

**Comment by pharsh** [comment]
Resolved;

**Comment by bob-moore** [comment]
Still getting same error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; Try it on your machine. Go to checkin, pick a reservation from the list of todays reservations, pick a room and click "check in"...open the chrome javascript console, and it should log any errors you get. Ran update.sql twice to be sure.

**Comment by bob-moore** [comment]
Got it solved...it was a single missing coma in the PHP file. Procedure works great!

**Comment by pharsh** [comment]
Stored procedure was fin, there was a missing comma in the php
